{"name": "test_playout_print[chromium]", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.189.200.6', port=80): Max retries exceeded with url: /api/v1/authenticate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1120c0a50>: Failed to establish a new connection: [Errno 51] Network is unreachable'))", "trace": "E   OSError: [Errno 51] Network is unreachable\n\nThe above exception was the direct cause of the following exception:\nE   urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x1120c0a50>: Failed to establish a new connection: [Errno 51] Network is unreachable\n\nThe above exception was the direct cause of the following exception:\nE   urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='10.189.200.6', port=80): Max retries exceeded with url: /api/v1/authenticate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1120c0a50>: Failed to establish a new connection: [Errno 51] Network is unreachable'))\n\nDuring handling of the above exception, another exception occurred:\nE   requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.189.200.6', port=80): Max retries exceeded with url: /api/v1/authenticate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1120c0a50>: Failed to establish a new connection: [Errno 51] Network is unreachable'))"}, "parameters": [{"name": "browser_name", "value": "'chromium'"}], "start": 1758887139765, "stop": 1758887139765, "uuid": "88c09f3d-a3d8-49c0-9f55-64309c855d45", "historyId": "68538b8ec41b77b27c3f6b964d7cf6a2", "testCaseId": "61f5ccf36914eb5db78c9c5e32107c07", "fullName": "tests.Automation_tests.test_history#test_playout_print", "labels": [{"name": "feature", "value": "History"}, {"name": "parentSuite", "value": "tests.Automation_tests"}, {"name": "suite", "value": "test_history"}, {"name": "host", "value": "TR-GKJF6LPM4P"}, {"name": "thread", "value": "62852-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.Automation_tests.test_history"}]}