{"uid":"91b28199d3bc2ec2","name":"test_playout_print[chromium]","fullName":"tests.Automation_tests.test_history#test_playout_print","historyId":"68538b8ec41b77b27c3f6b964d7cf6a2","time":{"start":1758887139765,"stop":1758887139765,"duration":0},"status":"broken","statusMessage":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.189.200.6', port=80): Max retries exceeded with url: /api/v1/authenticate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1120c0a50>: Failed to establish a new connection: [Errno 51] Network is unreachable'))","statusTrace":"E   OSError: [Errno 51] Network is unreachable\n\nThe above exception was the direct cause of the following exception:\nE   urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x1120c0a50>: Failed to establish a new connection: [Errno 51] Network is unreachable\n\nThe above exception was the direct cause of the following exception:\nE   urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='10.189.200.6', port=80): Max retries exceeded with url: /api/v1/authenticate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1120c0a50>: Failed to establish a new connection: [Errno 51] Network is unreachable'))\n\nDuring handling of the above exception, another exception occurred:\nE   requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.189.200.6', port=80): Max retries exceeded with url: /api/v1/authenticate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1120c0a50>: Failed to establish a new connection: [Errno 51] Network is unreachable'))","flaky":false,"newFailed":false,"newBroken":true,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"delete_output_dir","time":{"start":1758886296768,"stop":1758886296768,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":false},{"name":"pytestconfig","time":{"start":1758886296768,"stop":1758886296768,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":false},{"name":"base_url","time":{"start":1758886296768,"stop":1758886296768,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":false},{"name":"check_if_secrets_are_loaded","time":{"start":1758886296769,"stop":1758886296769,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":false},{"name":"_verify_url","time":{"start":1758886296769,"stop":1758886296769,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":false},{"name":"test_setup","time":{"start":1758886296769,"stop":1758886297436,"duration":667},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":false},{"name":"rp_logger","time":{"start":1758886297436,"stop":1758886297437,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":false},{"name":"playwright","time":{"start":1758886297437,"stop":1758886297864,"duration":427},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":false},{"name":"browser_type_launch_args","time":{"start":1758886297437,"stop":1758886297437,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":false},{"name":"launch_browser","time":{"start":1758886297864,"stop":1758886297864,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":false},{"name":"browser_type","time":{"start":1758886297864,"stop":1758886297864,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":false},{"name":"browser","time":{"start":1758886297864,"stop":1758886298757,"duration":893},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":false},{"name":"admin_user","time":{"start":1758887139765,"stop":1758887139766,"duration":1},"status":"broken","statusMessage":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.189.200.6', port=80): Max retries exceeded with url: /api/v1/authenticate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1120c0a50>: Failed to establish a new connection: [Errno 51] Network is unreachable'))\n","statusTrace":"  File \"/Users/s.chethana/PycharmProjects/wnec_backend-automation/.venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/s.chethana/PycharmProjects/wnec_backend-automation/.venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/s.chethana/PycharmProjects/wnec_backend-automation/.venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/s.chethana/PycharmProjects/Data_Driven_Framework_WNEC/conftest.py\", line 125, in fixture_admin_user\n    tokenized_user = API(api_util.auto_admin_user[\"username\"], api_util.auto_admin_user[\"password\"])\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/s.chethana/PycharmProjects/Data_Driven_Framework_WNEC/helpers/api.py\", line 20, in __init__\n    self.token = get_access_token(username, password)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/s.chethana/PycharmProjects/Data_Driven_Framework_WNEC/helpers/api.py\", line 12, in get_access_token\n    token_request = requests.post(f\"{API_URL}/authenticate\", json=auth, verify=False, timeout=10)\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/s.chethana/PycharmProjects/wnec_backend-automation/.venv/lib/python3.11/site-packages/requests/api.py\", line 115, in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/s.chethana/PycharmProjects/wnec_backend-automation/.venv/lib/python3.11/site-packages/requests/api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/s.chethana/PycharmProjects/wnec_backend-automation/.venv/lib/python3.11/site-packages/requests/sessions.py\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/s.chethana/PycharmProjects/wnec_backend-automation/.venv/lib/python3.11/site-packages/requests/sessions.py\", line 703, in send\n    r = adapter.send(request, **kwargs)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/s.chethana/PycharmProjects/wnec_backend-automation/.venv/lib/python3.11/site-packages/requests/adapters.py\", line 700, in send\n    raise ConnectionError(e, request=request)\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":true}],"afterStages":[{"name":"browser::0","time":{"start":1758887139809,"stop":1758887149881,"duration":10072},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":false},{"name":"playwright::0","time":{"start":1758887149883,"stop":1758887149885,"duration":2},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":false},{"name":"test_setup::0","time":{"start":1758887149887,"stop":1758887149890,"duration":3},"status":"broken","statusMessage":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.189.200.6', port=80): Max retries exceeded with url: /api/v1/authenticate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1120c07d0>: Failed to establish a new connection: [Errno 51] Network is unreachable'))\n","statusTrace":"  File \"/Users/s.chethana/PycharmProjects/wnec_backend-automation/.venv/lib/python3.11/site-packages/allure_commons/_allure.py\", line 231, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/s.chethana/PycharmProjects/wnec_backend-automation/.venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 911, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/s.chethana/PycharmProjects/Data_Driven_Framework_WNEC/conftest.py\", line 101, in fixture_test_setup\n    FileDistributor().remove_all_disribution_process()\n  File \"/Users/s.chethana/PycharmProjects/Data_Driven_Framework_WNEC/component_util/file_distributor.py\", line 74, in remove_all_disribution_process\n    response, status = API().get(\"/distributionprocesses\")\n                       ^^^^^\n  File \"/Users/s.chethana/PycharmProjects/Data_Driven_Framework_WNEC/helpers/api.py\", line 20, in __init__\n    self.token = get_access_token(username, password)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/s.chethana/PycharmProjects/Data_Driven_Framework_WNEC/helpers/api.py\", line 12, in get_access_token\n    token_request = requests.post(f\"{API_URL}/authenticate\", json=auth, verify=False, timeout=10)\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/s.chethana/PycharmProjects/wnec_backend-automation/.venv/lib/python3.11/site-packages/requests/api.py\", line 115, in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/s.chethana/PycharmProjects/wnec_backend-automation/.venv/lib/python3.11/site-packages/requests/api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/s.chethana/PycharmProjects/wnec_backend-automation/.venv/lib/python3.11/site-packages/requests/sessions.py\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/s.chethana/PycharmProjects/wnec_backend-automation/.venv/lib/python3.11/site-packages/requests/sessions.py\", line 703, in send\n    r = adapter.send(request, **kwargs)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/s.chethana/PycharmProjects/wnec_backend-automation/.venv/lib/python3.11/site-packages/requests/adapters.py\", line 700, in send\n    raise ConnectionError(e, request=request)\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":true}],"labels":[{"name":"feature","value":"History"},{"name":"parentSuite","value":"tests.Automation_tests"},{"name":"suite","value":"test_history"},{"name":"host","value":"TR-GKJF6LPM4P"},{"name":"thread","value":"62852-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.Automation_tests.test_history"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"browser_name","value":"'chromium'"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[]}],"history":{"statistic":{"failed":0,"broken":19,"skipped":0,"passed":8,"unknown":0,"total":27},"items":[{"uid":"33d2d7a79da1081b","status":"passed","time":{"start":1758884616228,"stop":1758884647375,"duration":31147}},{"uid":"d6b21e06ff4ec5a9","status":"passed","time":{"start":1758883283145,"stop":1758883314362,"duration":31217}},{"uid":"e810f072f9b28395","status":"broken","statusDetails":"playwright._impl._errors.TimeoutError: Locator.click: Timeout 30000ms exceeded.\nCall log:\nwaiting for locator(\"//*[@id=\\\"app-root\\\"]/div[3]/main/div[2]/article/div/div[2]/div[1]/div[1]/button\")","time":{"start":1758883004302,"stop":1758883040962,"duration":36660}},{"uid":"587a3bbd67cc12cd","status":"passed","time":{"start":1758806314743,"stop":1758806367242,"duration":52499}},{"uid":"e21d9331a9b92123","status":"broken","statusDetails":"playwright._impl._errors.TimeoutError: Locator.click: Timeout 30000ms exceeded.\nCall log:\nwaiting for locator(\"//*[@id=\\\"app-root\\\"]/div[3]/main/div[2]/article/div/div[2]/div[1]/div[1]/button\")","time":{"start":1758711118298,"stop":1758711154956,"duration":36658}},{"uid":"973dad71d204bb03","status":"passed","time":{"start":1758548452676,"stop":1758548532217,"duration":79541}},{"uid":"43898de13cfbd50a","status":"passed","time":{"start":1758524604682,"stop":1758524656855,"duration":52173}},{"uid":"cac8cfa7be7a5ae1","status":"passed","time":{"start":1758522631406,"stop":1758522684928,"duration":53522}},{"uid":"e353c0aaf0b1caf3","status":"passed","time":{"start":1758521016592,"stop":1758521108205,"duration":91613}},{"uid":"76e86f8ef24b0772","status":"broken","statusDetails":"playwright._impl._errors.TimeoutError: Locator.click: Timeout 30000ms exceeded.\nCall log:\nwaiting for locator(\"//dialog[@class=\\\"inv-bg\\\"]//div//div[@class=\\\"row buttons\\\"]//button[2]\")","time":{"start":1758520691521,"stop":1758520738368,"duration":46847}},{"uid":"b58e4f5066e71a00","status":"passed","time":{"start":1758518482308,"stop":1758518573122,"duration":90814}},{"uid":"b0addfa76c33d8d7","status":"broken","statusDetails":"playwright._impl._errors.TimeoutError: Locator.click: Timeout 30000ms exceeded.\nCall log:\nwaiting for locator(\"//dialog[@class=\\\"inv-bg\\\"]//div//div[@class=\\\"row buttons\\\"]//button[2]\")","time":{"start":1758518317900,"stop":1758518364992,"duration":47092}},{"uid":"30e0060132fe37fa","status":"broken","statusDetails":"playwright._impl._errors.TimeoutError: Locator.text_content: Timeout 30000ms exceeded.\nCall log:\nwaiting for locator(\"//div[@class=\\\"slug-edit-number row\\\"]//span[@class=\\\"wbreak\\\"]\").nth(3)","time":{"start":1758517884760,"stop":1758518001422,"duration":116662}},{"uid":"dc28d1d57779cdf9","status":"broken","statusDetails":"playwright._impl._errors.TimeoutError: Locator.click: Timeout 30000ms exceeded.\nCall log:\nwaiting for locator(\"//dialog[@class=\\\"inv-bg\\\"]//div//div[@class=\\\"row buttons\\\"]//button[2]\")","time":{"start":1758517804767,"stop":1758517851494,"duration":46727}},{"uid":"c7dc3cce466ae71e","status":"broken","statusDetails":"playwright._impl._errors.TimeoutError: Locator.text_content: Timeout 30000ms exceeded.\nCall log:\nwaiting for locator(\"//div[@class=\\\"slug-edit-number row\\\"]//span[@class=\\\"wbreak\\\"]\").nth(2)","time":{"start":1758517601744,"stop":1758517673611,"duration":71867}},{"uid":"528518cfd4d4838a","status":"broken","statusDetails":"playwright._impl._errors.TimeoutError: Locator.click: Timeout 30000ms exceeded.\nCall log:\nwaiting for locator(\"//dialog[@class=\\\"inv-bg\\\"]//div//div[@class=\\\"row buttons\\\"]//button[2]\")","time":{"start":1758517518473,"stop":1758517565194,"duration":46721}},{"uid":"19e46babbbd19b31","status":"broken","statusDetails":"playwright._impl._errors.TimeoutError: Locator.click: Timeout 30000ms exceeded.\nCall log:\nwaiting for locator(\"//dialog[@class=\\\"inv-bg\\\"]//div//div[@class=\\\"row buttons\\\"]//button[2]\")","time":{"start":1757326843210,"stop":1757326888611,"duration":45401}},{"uid":"d3bba312a41909c1","status":"broken","statusDetails":"playwright._impl._errors.TimeoutError: Locator.click: Timeout 30000ms exceeded.\nCall log:\nwaiting for locator(\"//dialog[@class=\\\"inv-bg\\\"]//div//div[@class=\\\"row buttons\\\"]//button[2]\")","time":{"start":1757316281911,"stop":1757316326403,"duration":44492}},{"uid":"ab7d50699fc873fa","status":"broken","statusDetails":"playwright._impl._errors.TimeoutError: Locator.click: Timeout 30000ms exceeded.\nCall log:\nwaiting for locator(\"//dialog[@class=\\\"inv-bg\\\"]//div//div[@class=\\\"row buttons\\\"]//button[2]\")","time":{"start":1756119138445,"stop":1756119183257,"duration":44812}},{"uid":"da2a36a7e1ae1dd2","status":"broken","statusDetails":"playwright._impl._errors.TimeoutError: Locator.click: Timeout 30000ms exceeded.\nCall log:\nwaiting for locator(\"//dialog[@class=\\\"inv-bg\\\"]//div//div[@class=\\\"row buttons\\\"]//button[2]\")","time":{"start":1756102796385,"stop":1756102842084,"duration":45699}}]},"tags":[]},"source":"91b28199d3bc2ec2.json","parameterValues":["'chromium'"]}